"""
Django settings for sanctiontracker project.

Generated by 'django-admin startproject'.
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR_STR = str(BASE_DIR)

SECRET_KEY = 'django-insecure-mya8d15%lauz4ii5qaonq!ssgj6@he*o!gi+4(-6ajpuapikd9'
DEBUG = True
ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'authentication.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sanctiontracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR_STR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sanctiontracker.wsgi.application'


# =========================
# Database
# =========================
DB_ENGINE = (os.environ.get("DB_ENGINE") or "postgresql").strip().lower()

if DB_ENGINE in {"postgres", "postgresql"}:
    db_defaults = {
        "DB_NAME": "sanction_tracker_db",
        "DB_USER": "sanction_user",
        "DB_PASSWORD": "1234",
        "DB_HOST": "localhost",
        "DB_PORT": "5432",
    }
    db_config = {key: os.environ.get(key) or default for key, default in db_defaults.items()}
    missing = [key for key, value in db_config.items() if not value]
    if missing:
        raise ImproperlyConfigured(
            "PostgreSQL selected (DB_ENGINE) but missing env vars: " + ", ".join(missing)
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": db_config["DB_NAME"],
            "USER": db_config["DB_USER"],
            "PASSWORD": db_config["DB_PASSWORD"],
            "HOST": db_config["DB_HOST"],
            "PORT": db_config["DB_PORT"],
        }
    }

elif DB_ENGINE == "sqlite3":
    sqlite_path = os.environ.get("DB_FILE_PATH")
    sqlite_path = Path(sqlite_path) if sqlite_path else (BASE_DIR / "db.sqlite3")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": sqlite_path,
        }
    }
else:
    raise ImproperlyConfigured(f"Unsupported DB_ENGINE value: {DB_ENGINE}")


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR_STR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR_STR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR_STR, 'media')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =========================
# Email (Gmail SMTP)
# =========================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "noejohnrubio@gmail.com")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")  # <-- IMPORTANT
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
