# Generated by Django 6.0.1 on 2026-02-15 06:20

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_sync_admin_access_flags'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
    ]
