# Generated by Django 5.1.7 on 2026-02-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_sanction_sanctiontype_user_course_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehoursubmission',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='service_hours/proofs/'),
        ),
    ]
